// API 统一出口：聚合并导出所有请求模块及类型安全的请求助手。
export * from './types'
export { authApi } from './auth'
export { docsApi } from './docs'
export { categoriesApi } from './categories'
export { chatApi } from './chat'
export { learningApi } from './learning'
export { knowledgeApi } from './knowledge'
export { knowledgeImportApi } from './knowledgeImport'
export { userApi } from './user'
export { adminApi } from './admin'
export type { IconVO } from './admin'
export { aiConfigApi } from './aiConfig'
export { codeAgentApi, msg } from './codeAgent'
export type { AgentStreamCallbacks } from './codeAgent'
export { ollamaApi } from './ollama'
export { studyGroupApi } from './studyGroup'
export { rankApi } from './ranking'
export { imApi } from './im'
export { quizApi } from './quiz'
export type { QuizPracticeVO, QuizAnswerItem, QuizResultItem, QuizSubmitResult, QuizStats } from './quiz'
export { checkinApi } from './checkin'
export type { CheckInResult, CheckInStatus } from './checkin'
export { habitApi } from './habit'
export type { HabitVO, HabitPayload, DayProgress } from './habit'
export { focusSessionApi } from './focusSession'
export { localReaderApi } from './localReader'
export type { TreeNode, FlatDoc, ScanResult, ResolveResult, DocContent } from './localReader'
export { achievementApi } from './achievement'
export { mistakesApi } from './mistakes'
export { fileApi } from './file'
export type { UploadFileVO, UploadStatsVO, UploadConfigVO, FileListResult } from './file'
export { default as request, apiGet, apiPost, apiPut, apiDelete } from './request'
