// API 统一出口：聚合并导出所有请求模块及类型安全的请求助手。
export * from './types'
export { authApi } from './auth'
export { docsApi } from './docs'
export { categoriesApi } from './categories'
export { chatApi } from './chat'
export { learningApi } from './learning'
export { knowledgeApi } from './knowledge'
export { userApi } from './user'
export { adminApi } from './admin'
export type { IconVO } from './admin'
export { aiConfigApi } from './aiConfig'
export { studyGroupApi } from './studyGroup'
export { rankApi } from './ranking'
export { imApi } from './im'
export { quizApi } from './quiz'
export type { QuizPracticeVO, QuizAnswerItem, QuizResultItem, QuizSubmitResult, QuizStats } from './quiz'
export { checkinApi } from './checkin'
export type { CheckInResult, CheckInStatus } from './checkin'
export { focusSessionApi } from './focusSession'
export { achievementApi } from './achievement'
export { mistakesApi } from './mistakes'
export { default as request, apiGet, apiPost, apiPut, apiDelete } from './request'
